#!/bin/bash

WORKSHOP=../../../workshop/content/211820
MODS=../mods


if [ "$1" == "unlink" ]; then
	[ -z "$(ls $MODS | grep -o ".pak")" ] || rm $MODS/*.pak
	exit 0
fi

folders=$(ls $WORKSHOP)
i=0
[ -z "$(ls $MODS | grep -o ".pak")" ] || rm $MODS/*.pak


for f in ${folders[@]}; do

	fn="$(ls $WORKSHOP/$f -l)"
	fn="$(grep -oE "^.*(.pak)" <<< $fn)"
	fn="$(sed -E "s/^.*[0-9]{2}(:)[0-9]{2}\s{1}//g" <<< $fn )"
	filenumber=1
	while IFS= read -r af; do
		ln -s "$WORKSHOP/$f/$af" "$MODS/$f-$i""_$filenumber-$af"
		filenumber=$(($filenumber+1))
	done <<< "$fn"


	if [ $filenumber -gt 2 ]; then
		echo -e "\e[1m\e[32mMod $f has $(($filenumber-1)) files"
		while IFS= read -r af; do
			echo -e "\e[1m\e[94m$f/$af\e[0m"
		done <<< "$fn"
	fi


	i=$(($i+1))

done
echo -e "\e[1m\e[32mAdded $i mods"
