#!/bin/bash

#
# MIT License
#
# Copyright (c) 2022 Reiikz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

VERSION="sid-(development version)"
COPYRIGHT_YEAR="2022"
SOURCE_URL="https://github.com/Reiikz/your-awesm"
ERROR_REPORTING_TO="https://github.com/Reiikz/your-awesm/issues"
DOCUMENTATION="https://github.com/Reiikz/your-awesm/wiki"
CONFIGVER=2
BUILT_FROM="(NON PACKAGED VERSION)"

#STARBOUND APP ID, this is the Game's APP ID and it is used to download mods, do not change it
APPID=211820

# ~~~~~~~~~~~~~~~~~~~~~~~ SCRIPT STARTS HERE

#load up main library
if ! source "$MAIN_LIBRARY"; then
	echo -e "$FC_RED$FC_BOLD""Could not load main library"
	exit 0;
fi

MY_UID="your-awesm.$(basename ${BASH_SOURCE[0]}).$$"
MYSELF="$(basename ${BASH_SOURCE[0]})"
MY_SOURCE="${BASH_SOURCE[0]}"
USER_HOME="$(getent passwd $(whoami) | cut -d':' -f6)"

CONFIG_DIR="$USER_HOME/.config/RZ.star-server/$CONFIGVER"
CACHE_DIR="$USER_HOME/.cache/RZ.star-server-cache"
SERVER_WORKERS="$USER_HOME/.local/lib/RZ.star-server/1/server_workers"
mkdir -p $CONFIG_DIR
COLORFUL=1

RECOMMEND_COOL_MODS="yes"
declare -ga COOLMODS=( [0]="1958993491" )
declare -gA COOLMODS_REASON=( [1958993491]="the maker of $MYSELF is an 8 headed dragon and this is an awesome dragon race, you should totally try it" )

INSTALL_PREFIX="/usr/local"

UNIT_FILE_TEMPLATE="$INSTALL_PREFIX/lib/reiikz/your-awesm/templates/template-unit-file.service"
MAIN_LIBRARY="$INSTALL_PREFIX/lib/reiikz/your-awesm/common"

if [ -f "$CONFIG_DIR/CLIENT_PRERUN" ]; then
	source "$CONFIG_DIR/CLIENT_PRERUN"
fi