#!/bin/bash

#
# MIT License
#
# Copyright (c) 2022 Reiikz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

#######################################################################
######			---------------------------------------------         #
######							ATENTION                              #
######			---------------------------------------------         #
######		THIS IS JUST A LIBRARY CONTAINGING FUNCTIONS AND SHOULD   #
######      NOT BE RAN MANUALLY 									  #
######																  #
#######################################################################

# SOURCE_URL="https://github.com/Reiikz/your-awesm"
# ERROR_REPORTING_TO="https://github.com/Reiikz/your-awesm/issues"

# filesystem handling, (copying, linking, comparing)

BASH_QOL_FILE_HANDLEING_VERSION="0.0.1"

if [ -z "${BASH_QOL_LIBRARIES[@]}" ]; then
    declare -gA BASH_QOL_LIBRARIES=( [fileHandling]="$BASH_QOL_FILE_HANDLEING_VERSION" )
else
    BASH_QOL_LIBRARIES[fileHandling]="$BASH_QOL_FILE_HANDLEING_VERSION"
fi

if [ -z "${BASH_QOL_LIBRARIES[common]}" ]; then
    echo "BashQoL: file handling requires common library"
    exit 200
fi

function linkify {
    if [ "$COPY" == "1" ]; then
        if ! cp -r "$1" "$2"; then
			coecho "$FC_RED$FC_BOLD" "could not copy: \"$1\" to \"$2\""
			return 1
		fi
    else
        if ! ln -s "$(realpath --no-symlinks "$1")" "$(realpath --no-symlinks "$2")"; then
			coecho "$FC_RED$FC_BOLD" "could not link: \"$1\" to \"$2\""
			return 1
		fi
    fi
}

#usage: isDirChildOf $parentDIr $childDir
function isDirChildOf {

    local parent="$(realpath -P "$1")"
    local child="$(realpath -P "$2")"

    case $child in
        "$parent"/*)
            return 0    
        ;;
        *)
            return 1
        ;;
    esac

}